Repository IIC3745-Grupo-5/ProyectoB, pull requests merged in 2021-11, with the labels that each got.

#2 Movies
  app/assets/stylesheets/cinemas.scss
  app/assets/stylesheets/movies.scss
  app/controllers/movies_controller.rb
  app/views/cinemas/show.html.erb
  app/views/movies/show.html.erb
  db/seeds.rb
Labels: enhancement

#3 test: added first rspec + capybara tests
  .rspec
  Gemfile
  Gemfile.lock
  app/views/cinemas/show.html.erb
  spec/cinemas_spec.rb
  spec/movies_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/controllers/cinemas_controller_test.rb
  test/controllers/movies_controller_test.rb
  test/controllers/reservations_controller_test.rb
  test/controllers/rooms_controller_test.rb
  test/controllers/schedules_controller_test.rb
  test/fixtures/cinemas.yml
  test/fixtures/files/.keep
  test/fixtures/movies.yml
  test/fixtures/reservations.yml
  test/fixtures/rooms.yml
  test/fixtures/schedules.yml
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/models/cinema_test.rb
  test/models/movie_test.rb
  test/models/reservation_test.rb
  test/models/room_test.rb
  test/models/schedule_test.rb
  test/system/.keep
  test/system/cinemas_test.rb
  test/system/movies_test.rb
  test/system/reservations_test.rb
  test/system/rooms_test.rb
  test/system/schedules_test.rb
  test/test_helper.rb
Labels: test

#6 Fix/react components not loading at first
  Gemfile
  Gemfile.lock
  app/javascript/packs/application.js
  app/views/layouts/application.html.erb
  docs/pull_request_template.md
  package.json
  yarn.lock
Labels: bug fix

#8 Show reserved seats.
  app/assets/stylesheets/rooms.scss
  app/controllers/reservations_controller.rb
  app/controllers/rooms_controller.rb
  app/javascript/packs/room.jsx
  app/javascript/packs/seat.jsx
  app/views/rooms/show.html.erb
Labels: enhancement
